[test]
# Always enable coverage
coverage = true

# Set coverage thresholds
coverageThreshold = { lines = 80, functions = 80, statements = 80, branches = 80 }

# Skip test files in coverage reports
coverageSkipTestFiles = true

# Coverage reporters
coverageReporter = ["text", "lcov"]

# Coverage directory
coverageDir = "./coverage"
